### ISSUE TITLE
Robozonky nefunguje s chybějící hodnotou (a nebo < 200) minimumBalance

### ISSUE THREAD

**Issue by frantisekz** [triceo/robozonky#35]
Pokud jsem vše správně pochopil, tak by dávalo i smysl i když by byla hodnota minimumBalance menší než 200. Pokud ji však takto nastavím, a nebo vynechám v investiční startegii úplně, tak robozonky skončí s (pokud je hodnota menší než 200, tak se jen změní chybová zpráva):
```
15:10:30.985 ERROR Failed parsing strategy.
com.github.triceo.robozonky.strategy.InvestmentStrategyParseException: java.lang.IllegalStateException: Minimum balance is missing.
	at com.github.triceo.robozonky.strategy.simple.SimpleInvestmentStrategyService.parse(SimpleInvestmentStrategyService.java:216)
	at com.github.triceo.robozonky.strategy.InvestmentStrategyLoader.load(InvestmentStrategyLoader.java:47)
	at com.github.triceo.robozonky.strategy.InvestmentStrategy.load(InvestmentStrategy.java:43)
	at com.github.triceo.robozonky.app.OperatingMode$1.setup(OperatingMode.java:64)
	at com.github.triceo.robozonky.app.App.processCommandLine(App.java:130)
	at com.github.triceo.robozonky.app.App.main(App.java:136)
Caused by: java.lang.IllegalStateException: Minimum balance is missing.
	at com.github.triceo.robozonky.strategy.simple.SimpleInvestmentStrategyService.lambda$getMinimumBalance$2(SimpleInvestmentStrategyService.java:108)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.github.triceo.robozonky.strategy.simple.SimpleInvestmentStrategyService.getMinimumBalance(SimpleInvestmentStrategyService.java:108)
	at com.github.triceo.robozonky.strategy.simple.SimpleInvestmentStrategyService.parse(SimpleInvestmentStrategyService.java:208)
	... 5 common frames omitted
```

**Comment by triceo** [comment]
Obojí je záměrné - vynechat hodnotu znamená, že je strategie nekompletní, a program tedy selže. Důvodem je přimět uživatele, aby vždy nadefinovali vše zcela přesně - a nemohli tedy později lamentovat, že robot udělal nějaká nepřípustná rozhodnutí za ně. Tam myslím není o čem diskutovat.

U té druhé možnosti - tj. u `minimumBalance` pod 200,- Kč - by se dalo diskutovat, jestli má program v takovém případě selhat. Osobně se domnívám, že ano, protože taková hodnota nedává na `Zonky` smysl. Nicméně si rád poslechnu protiargument.

Každopádně děkuji za nahlášení, je dobré o věcech mluvit.

**Comment by frantisekz** [comment]
Jo, jasně, nějak jsem si neuvědomil, že se nedá stejně investovat částka < 200 .

Díky za odpověď :)
