### ISSUE TITLE
RoboZonky přestalo fungovat ("OTHERS_MAIN")

### ISSUE THREAD

**Issue by frantisekz** [triceo/robozonky#36]
Nevím, jestli Zonky nezměnilo nějak své API (včera večer byl krátkodobý výpadek webu, ale dnes ráno ještě RoboZonky fungoval), ale dnes kolem poledne přestalo RoboZonky fungovat. Podle chyby bych to tipoval, že Zonky přidalo další typ příjmu ("OTHERS_MAIN").

Fix je tady #37 .

Napadlo mne, jestli by nešlo RoboZonky upravit tak, aby bylo robustnější, a zvládlo fungovat i s neznámým typem příjmu?

```
13:35:18.909 ERROR Unexpected error.
javax.ws.rs.client.ResponseProcessingException: javax.ws.rs.ProcessingException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of com.github.triceo.robozonky.remote.MainIncomeType from String value 'OTHERS_MAIN': value not one of declared Enum instance names: [ENTREPRENEUR, EMPLOYMENT, PENSION, SELF_EMPLOYMENT]
 at [Source: org.apache.http.conn.EofSensorInputStream@10cf09e8; line: 1, column: 620] (through reference chain: java.util.ArrayList[0]->com.github.triceo.robozonky.remote.Loan["mainIncomeType"])
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:141)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:60)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy35.getLoans(Unknown Source)
	at com.github.triceo.robozonky.Investor.investOnce(Investor.java:176)
	at com.github.triceo.robozonky.Investor.invest(Investor.java:205)
	at com.github.triceo.robozonky.app.App.invest(App.java:217)
	at com.github.triceo.robozonky.app.App.main(App.java:146)
Caused by: javax.ws.rs.ProcessingException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of com.github.triceo.robozonky.remote.MainIncomeType from String value 'OTHERS_MAIN': value not one of declared Enum instance names: [ENTREPRENEUR, EMPLOYMENT, PENSION, SELF_EMPLOYMENT]
 at [Source: org.apache.http.conn.EofSensorInputStream@10cf09e8; line: 1, column: 620] (through reference chain: java.util.ArrayList[0]->com.github.triceo.robozonky.remote.Loan["mainIncomeType"])
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:285)
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readEntity(ClientResponse.java:181)
	at org.jboss.resteasy.specimpl.BuiltResponse.readEntity(BuiltResponse.java:213)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:105)
	... 8 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of com.github.triceo.robozonky.remote.MainIncomeType from String value 'OTHERS_MAIN': value not one of declared Enum instance names: [ENTREPRENEUR, EMPLOYMENT, PENSION, SELF_EMPLOYMENT]
 at [Source: org.apache.http.conn.EofSensorInputStream@10cf09e8; line: 1, column: 620] (through reference chain: java.util.ArrayList[0]->com.github.triceo.robozonky.remote.Loan["mainIncomeType"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:55)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:907)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:130)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:84)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1470)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:912)
	at org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.readFrom(ResteasyJackson2Provider.java:121)
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:61)
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:53)
	at org.jboss.resteasy.plugins.interceptors.encoding.GZIPDecodingInterceptor.aroundReadFrom(GZIPDecodingInterceptor.java:59)
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:55)
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:251)
	... 11 common frames omitted
```

**Comment by triceo** [comment]
Domnívám se, že úprava RoboZonky, aby takhle nepodstatnou položku vůbec neřešil, bude nevyhnutelná. Takovéhle selhání jednou týdně je zkrátka nepřijatelné.

Každopádně díky za opravu, vydám novou verzi.
