### ISSUE TITLE
NullPointer

### ISSUE THREAD

**Issue by buggyb12** [triceo/robozonky#46]
Kdyz nemam jeste zadne pujcky a pustim robozonky obdrzim:

14:12:55.114 [main] ERROR com.github.triceo.robozonky.app.App Unexpected error.
java.lang.NullPointerException: null
	at com.github.triceo.robozonky.Operations.calculateSharesPerRating(Operations.java:101)
	at com.github.triceo.robozonky.Operations.identifyLoanToInvest(Operations.java:228)
	at com.github.triceo.robozonky.Operations.invest(Operations.java:292)
	at com.github.triceo.robozonky.app.App.invest(App.java:194)
	at com.github.triceo.robozonky.app.App.main(App.java:132)
14:12:55.114 [main] DEBUG com.github.triceo.robozonky.app.App RoboZonky terminating with 'ERROR_UNEXPECTED' return code.

**Comment by buggyb12** [comment]
stara verze 1.2.1 ... po update uz funguje jak ma ...

**Comment by triceo** [comment]
1.2.1 už je skutečně poněkud stará a vybavuji si, že tenhle problém skutečně měla. 
I tak díky za nahlášení!
