### ISSUE TITLE
Unexpected error. java.lang.IllegalStateException: Duplicate key Investment

### ISSUE THREAD

**Issue by jvyoralek** [triceo/robozonky#48]
V kontextu této chyby bohužel mám logování jen na úrovni INFO, ale snad to i tak pomůže:

15:39:09.607 [main] INFO  c.g.t.r.operations.InvestOperation Invested 400 CZK into loan 43036.
15:39:09.667 [main] ERROR com.github.triceo.robozonky.app.App Unexpected error.
java.lang.IllegalStateException: Duplicate key Investment{amountDue=null, currentTerm=34, dpd=0, interestRate=0.084900, loanName='Refinancování půjček', loanTermInMonth=34, rating=AA, paymentStatus='OK'} extends BaseInvestment{id=258751, loanId=42893, amount=200}
	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
	at java.util.HashMap.merge(HashMap.java:1253)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.github.triceo.robozonky.Investor.mergeInvestments(Investor.java:67)
	at com.github.triceo.robozonky.Investor.invest(Investor.java:213)
	at com.github.triceo.robozonky.app.App.invest(App.java:171)
	at com.github.triceo.robozonky.app.App.core(App.java:72)
	at com.github.triceo.robozonky.app.App.main(App.java:87)
15:39:09.681 [main] INFO  com.github.triceo.robozonky.app.App Your version of RoboZonky seems up to date.

Budou-li prospěšné nějaké další detaily pokusím se s tím pomoct.

Díky
J.

**Comment by triceo** [comment]
Díky za nahlášení, podívám se na to příští týden po návratu z dovolené.
