### ISSUE TITLE
Chování robozonkyho při údržbě webu zonky.cz

### ISSUE THREAD

**Issue by jvyoralek** [triceo/robozonky#49]
Měl bych námět na vylepšení. Občas se stává, že zonky nasazuje na web novou verzi a úplně se s tím nemažou a ne několik minut/hodin web vypnou s touto hláškou:
![image](https://cloud.githubusercontent.com/assets/15640266/17909795/5dd349c6-6986-11e6-998d-b020c8b35f32.png)

Chudák robozonky pak začne nemilosrdně padat na ústa s chybou:
```
ERROR Failed. 
javax.ws.rs.NotAllowedException: HTTP 405 Method Not Allowed 
at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:203) 
at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:174) 
at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:60) 
at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104) 
at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76) 
at com.sun.proxy.$Proxy24.login(Unknown Source) 
at com.github.triceo.robozonky.authentication.Authenticator.lambda$withCredentials$0(Authenticator.java:63) 
at com.github.triceo.robozonky.authentication.Authenticator.authenticate(Authenticator.java:156) 
at com.github.triceo.robozonky.authentication.Authenticator.authenticate(Authenticator.java:169) 
at com.github.triceo.robozonky.operations.LoginOperation.perform(LoginOperation.java:38) 
at com.github.triceo.robozonky.operations.LoginOperation.perform(LoginOperation.java:24) 
at com.github.triceo.robozonky.operations.Operation.apply(Operation.java:34) 
at com.github.triceo.robozonky.app.authentication.AuthenticationHandler.login(AuthenticationHandler.java:207) 
at com.github.triceo.robozonky.app.App.invest(App.java:166) 
at com.github.triceo.robozonky.app.App.core(App.java:72) 
at com.github.triceo.robozonky.app.App.main(App.java:87) 
22:04:06.864 ERROR Application encountered an error during setup. 
com.github.triceo.robozonky.app.util.UnrecoverableRoboZonkyException: Login failed. 
at com.github.triceo.robozonky.app.authentication.AuthenticationHandler.login(AuthenticationHandler.java:209) 
at com.github.triceo.robozonky.app.App.invest(App.java:166) 
at com.github.triceo.robozonky.app.App.core(App.java:72) 
at com.github.triceo.robozonky.app.App.main(App.java:87) 
```

Bylo by fajn, kdyby to neskončilo error hláškou, ale pro tento případ by mohl stačit warning. Chodí mě emaily pokud robot spadne, takže jsem pak zavalen :)

Díky
J.

**Comment by triceo** [comment]
Dobrý den, také mi chodí e-maily, jsme ve stejné situaci.

Bohužel jsem zatím nepřišel na to, jak **spolehlivě** detekovat, že _Zonky_ provádí údržbu. Budu-li v nějaké situaci cíleně ignorovat chybové stavy, chci si být zatraceně jistý, že žádná skutečná chyba neunikne pozornosti - máte-li nápad, jak detekovat údržbu, rád si jej poslechnu.

Osobně jsem zatím vypozoroval, že chování při údržbě může být různé. Pokud se přihlašujete heslem, nepovede se vám login - ale někdy ano, a selže to třeba až v peněžence. Pokud se přihlašujete OAuth tokenem, selže to v peněžence. Pokud by ale takové chování bylo chybou v _RoboZonky_, uživatelé by to chtěli vědět - a to právě nevím, jak odlišit.

**Comment by frantisekz** [comment]
@triceo Možná trochu blbý řešení, ale nestačilo by stáhnout titulní stranu a zkusit v ní ověřit výskyt některé z vět, která se na chybové stránce typicky objevuje?

S programováním v Javě nemám absolutně žádné zkušenosti(takže to třeba nepůjde nějak jednoduše implementovat), ale kdybych psal Robozonkyho (v Pythonu) já, tak bych to asi řešil tímto způsobem.

**Comment by triceo** [comment]
Napsal jsem krátkou wiki o tom, jak to bude fungovat v RoboZonky 1.5.0:
https://github.com/triceo/robozonky/wiki/Tolerov%C3%A1n%C3%AD-chyb-v-s%C3%AD%C5%A5ov%C3%A9-komunikaci

**Comment by triceo** [comment]
(Na okraj: chtěl jsem se vyhnout tomu, abych načítal nějakou stránku a hledal v ní nějaký text. To je poměrně nespolehlivé a pomalé, pro robota se to podle mého názoru příliš nehodí. Proto jsem ten mechanismus napsal tak, aby hledal v konkrétních situacích konkrétní HTTP stavy. Zároveň jsem to implementoval tak, že je ta funkce ve výchozím nastavení vypnutá - kdo jí chce používat, musí se seznámit s tím, jaké může mít důsledky.)

**Comment by jvyoralek** [comment]
Nestihl jsem ani zareagovat, ale stejně bych k tomu technicky nebyl schopen cokoliv dodat, jelikož moc netuším jak to funguje. Každopádně díky moc za ten volitelný workaround.
