### ISSUE TITLE
Exception in thread "main" 

### ISSUE THREAD

**Issue by vivivicz** [triceo/robozonky#68]
Dobrý den, snažím se robozonky spustit na raspberry pi 3, zkouším různé OS (Raspbian, Ubuntu MATE), různé verze java ale vždy se vypíše tato chyba.

`Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: javax/ws/rs/ProcessingException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: javax.ws.rs.ProcessingException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more`

Aktuální verze java na Ubuntu MATE:
`java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) Client VM (build 25.111-b14, mixed mode)
`

Děkuji za pomoc.

**Comment by triceo** [comment]
Výjimka si stěžuje na to, že Vám chybí třída `javax/ws/rs/ProcessingException` - tahle třída ale je součástí souboru `jboss-jaxrs-api_2.0_spec-1.0.0.Final.jar`, který zase na oplátku je součástí `RoboZonky`. Tato výjimka tedy nemá jak nastat, pokud `RoboZonky` spouštíte správně.

Pamatujte, že musíte `RoboZonky` spouštět přes soubor `robozonky.sh`, a nikoliv přímo přes `java -jar`. `

**Comment by vivivicz** [comment]
Děkuji, ovšem spouštím právě přes robozonky.sh. 

`
petr@petr-desktop:~/zonky$ sh robozonky.sh
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: javax/ws/rs/Processin             gException
`

nebo 

`
petr@petr-desktop:~/zonky$ sh robozonky.sh -s test.cfg -u test -p "test"
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: javax/ws/rs/Processin             gException
`

Obsah robozonky.sh zůstal beze změn tedy:
`#!/bin/bash
BASEDIR=$(dirname "$0")
$JAVA_HOME/bin/java -Dlogback.configurationFile=logback.xml -Dfile.encoding="UTF-8" -Djava.net.preferIPv4Stack=true -Xmx64m -jar $BASEDIR/robozonky-app-1.6.0.jar "$@"`

Kde jinde tedy může být zakopaný pes? Není to právě díky procesoru ARM, co se řešilo v jiném tématu?

**Comment by triceo** [comment]
Ten ARM je opravený, to už by mělo fungovat - navíc to byla úplně jiná chyba, než tady.

Tady chybí knihovna, která prokazatelně v `RoboZonky` je. Když jsem jí smazal ze svojí instalace, dostal jsem přesně tuhle chybu. Takže Váš problém spočívá v tom, že z nějakého důvodu tu knihovnu nemáte. Proč, to nemám odsud jak zjistit.

Doporučuji zkontrolovat obsah adresáře `~/zonky/lib/`, protože přesně tam by se ta knihovna měla nacházet.

**Comment by vivivicz** [comment]
Děkuji moc, opravdu moje hloupá chyba a to jsem zkoušel mnoho řešení. Je to opravdu tím.

**Comment by triceo** [comment]
V pořádku, hlavně že jsme to vyřešili. :-)
