### ISSUE TITLE
E-Mail Sender - always  noreply@robozonky.cz - can cause troubles

### ISSUE THREAD

**Issue by AscifiA** [triceo/robozonky#83]
Ahoj, díky Lukáši za tvoji úžasnou práci.. Mám však jeden koment k nové funkci posílání e-mailů:

Pokud je Sender "noreply@robozonky.cz" tedy jiný než skutečně přihlášený uživatel k e-mailovému serveru, pak ho většina běžných e-malových serverů odmítne, jako pokus o SPAM, či útok.

**Viz např Centrum server (info z Logu Robozonky):**
Caused by: org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.centrum.cz:25
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1421)
	at org.apache.commons.mail.Email.send(Email.java:1448)
	at com.github.triceo.robozonky.notifications.email.AbstractEmailingListener.handle(AbstractEmailingListener.java:75)
	... 40 common frames omitted
Caused by: javax.mail.SendFailedException: Invalid Addresses
	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1949)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1195)
	at javax.mail.Transport.send0(Transport.java:254)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1411)
	... 42 common frames omitted
**Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 553 5.7.1 <noreply@robozonky.cz>: Sender address rejected: not owned by user xxxx.xxxx@atlas.cz**

Tedy v konfiguraci e-mailu, by měla být možnost pro tyto servery zadat odesílatele (většinou bude stejný jako e-mail to)

Pojal bych to asi takto:
v  config souboru "robozonky-notifications.cfg", bych zavedl standardní parametr "smtp.from"
a pokud není definováno tak vlož "noreply@robozonky.cz"

A  noreply@robozonky.cz  bych uváděl do Předmětu e-mailu - pro jasnou identifikaci.
Nebo bych také zavedl v config souboru "robozonky-notifications.cfg" parameter email.subject, aby si to každý mohl definovat případně sám, dle potřeby

M.P.

**Comment by triceo** [comment]
Zdravím! Shodou okolností mě na to dnes už někdo upozornil - já to testoval na GMailu a tam to jako na potvoru funguje. Opravím to snad do víkendu, díky za report!

**Comment by AscifiA** [comment]
Není zač... Rozumím.. Díky..
Proto většina seriózních serverů má s maily GMailu trvalé problémy, je nejvíce zneužíván k útokům :-)
