### ISSUE TITLE
Robozonky 3.0.0 alpha1 - Bad Request

### ISSUE THREAD

**Issue by khostri** [triceo/robozonky#91]
Ahoj
při zkoušení nové alfa verze pokaždé spuštění skončí na bad request (http error 400).
zkoušel jsem opakovaně, abych vyloučil chybu sítě. Vše jako single mode, daemona jsem nespouštěl.

`jmeno.prijmeni@synology:~/robozonky$ sh robozonky.sh -u jmeno.prijmeni@emailova.schranka -p SecurEpassw0rd single -s robozonky-risky.cfg
10:38:15.474 INFO  Using plain-text credentials when guarded storage available. Consider switching.
10:38:15.518 INFO  Guarded storage was created with your username and password: robozonky.keystore
10:38:16.548 INFO  RoboZonky v3.0.0-alpha-1 starting.
10:38:16.550 INFO  ===== RoboZonky at your service! =====
10:38:17.934 INFO  Authenticating as 'jmeno.prijmeni@emailova.schranka' using password.
10:38:19.086 ERROR Failed executing investments.
javax.ws.rs.BadRequestException: HTTP 400 Bad Request
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:212)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:189)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:60)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:107)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
        at com.sun.proxy.$Proxy32.login(Unknown Source)
        at com.github.triceo.robozonky.app.authentication.Authenticator.lambda$withCredentials$0(Authenticator.java:48)
        at com.github.triceo.robozonky.app.authentication.Authenticator.authenticate(Authenticator.java:92)
        at com.github.triceo.robozonky.app.authentication.AuthenticationHandler.execute(AuthenticationHandler.java:166)
        at com.github.triceo.robozonky.app.investing.StrategyExecution.invest(StrategyExecution.java:84)
        at com.github.triceo.robozonky.app.investing.StrategyExecution.apply(StrategyExecution.java:108)
        at com.github.triceo.robozonky.app.investing.StrategyExecution.apply(StrategyExecution.java:39)
        at com.github.triceo.robozonky.app.investing.AbstractInvestmentMode.lambda$execute$0(AbstractInvestmentMode.java:107)
        at com.github.triceo.robozonky.marketplaces.ZotifyMarketplace.lambda$run$0(ZotifyMarketplace.java:47)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at com.github.triceo.robozonky.marketplaces.ZotifyMarketplace.run(ZotifyMarketplace.java:47)
        at com.github.triceo.robozonky.app.investing.SingleShotInvestmentMode.openMarketplace(SingleShotInvestmentMode.java:59)
        at com.github.triceo.robozonky.app.investing.AbstractInvestmentMode.execute(AbstractInvestmentMode.java:110)
        at com.github.triceo.robozonky.app.investing.SingleShotInvestmentMode.execute(SingleShotInvestmentMode.java:53)
        at com.github.triceo.robozonky.app.investing.AbstractInvestmentMode.get(AbstractInvestmentMode.java:73)
        at com.github.triceo.robozonky.app.investing.SingleShotInvestmentMode.get(SingleShotInvestmentMode.java:35)
        at com.github.triceo.robozonky.app.investing.AbstractInvestmentMode.get(AbstractInvestmentMode.java:33)
        at com.github.triceo.robozonky.app.App.execute(App.java:82)
        at com.github.triceo.robozonky.app.App.lambda$execute$1(App.java:100)
        at java.util.Optional.map(Optional.java:215)
        at com.github.triceo.robozonky.app.App.execute(App.java:97)
        at com.github.triceo.robozonky.app.App.main(App.java:126)
`

**Comment by triceo** [comment]
Díky za report. Podívám se na to, jen co mi práce dovolí!

**Comment by triceo** [comment]
@khostri Zkoušel jsem stejnou věc u sebe a operace prošla v pořádku. Vzhledem k tomu, že se jedná o odmítnutí přihlášení serverem, nemůže být prostě špatné heslo?

V každém případě bych vás rád požádal o zaslání logu, ze kterého snad půjde vyčíst více.

**Comment by khostri** [comment]
Log mohu poslat, ale zarazí se to na 
`17:56:32.897 [main@10264@PC-HONZA] INFO  c.g.t.r.a.a.Authenticator Authenticating as 'jmeno@email.net' using password.
17:56:32.899 [main@10264@PC-HONZA] TRACE c.g.t.r.a.a.AuthenticationFilter Will 'POST' to 'https://api.zonky.cz/oauth/token'.
17:56:33.050 [main@10264@PC-HONZA] DEBUG c.g.t.r.a.a.AuthenticationFilter Operation 'POST' to 'https://api.zonky.cz/oauth/token' finished with HTTP 400.`

Změnil jsem heslo na zonky a to projde. Nemyslím si ale, že je to záležitost terminálu, protože chybu to hodí i ve Windows, což jsem si ověřil. Je jedno, jestli je heslo v uvozovkách nebo není.
moje původní heslo obsahovalo $ a !. Spíš jestli se něco nebere jako řídící znak v rámci zpracování dotazu.

podle mě podobný problém bude se související chybou ohledně hesla na keystore

**Comment by triceo** [comment]
To už zní zajímavěji. Ve volné chvíli se podívám, jak se chová RoboZonky, když jsou v hesle takové znaky.

**Comment by khostri** [comment]
pokud vygeneruji heslo bez speciálních znaků, tak to funguje jak má. Alespoň prozatím.
Napadlo mě, že to asi nebude jednoduše řešitelné, protože v rámci předávání parametrů cokoliv začínající na $ bere asi jako proměnnou.
Keystore s novým heslem také funguje. Je otázkou, jestli má smysl trávit čas tímto a nebo v dokumentaci poznamenat, že heslo nesmí obsahovat $
každopádně díky :)

**Comment by triceo** [comment]
@khostri Vyzkouším to. Nicméně mám dobrý zvyk heslo psát na příkazové řádce do uvozovek, což by (pokud si ještě správně pamatuju základy UNIXu) mělo problém s $ vyřešit.

**Comment by triceo** [comment]
Každopádně pokud by se ukázalo, že $ je vážně problém, tak dokumentaci opravím.

**Comment by khostri** [comment]
Uvozovky nepomohou podle mého. Příkazová řádka to do Bash scriptu předá v pohodě, ale tam je to jako parametr, tzn vyhodnocení v rámci scriptu si myslí, že je to nějaká proměnná. Asi...

**Comment by triceo** [comment]
Dopsal jsem poznámku k nastavení zabezpečení, a přidal do RoboZonky lepší výjimku v případě selhání autentizace.

Děkuji za nahlášení problému - speciální znaky v hesle mám, ale nenapadlo mne tam dát dolar. :-)
